# Experiment Configuration for PSS Watermark Detection

# Dataset parameters
dataset:
  source: "PG-19"
  num_samples: 1000
  skip_lines: 200
  word_per_sample: 4000
  split_ratio: 0.5    # Split between human and AI text

# Text length variations (in words)
text_lengths:
  - 1500  # Default after watermarking
  - 1000
  - 500
  - 300

# Paraphrasing parameters
paraphrasing:
  iterations: 8
  batch_size: 10
  save_frequency: 50
  temperature: 0.8
  top_p: 0.95
  model_context_size: 4096
  gpu_layers: -1  # Use all available GPU layers


# Rolling window parameters
rolling_window:
  window_size: 50
  stride: 10
  # Alternative configurations for sensitivity analysis
  sensitivity_configs:
    - window_size: 40
      stride: 5
    - window_size: 60
      stride: 15

# PSS method parameters
pss_method:
  static_features:
    - z_mean
    - z_var
    - z_min
    - z_max
    - z_skew
    - z_kurtosis
    - z_autocorr_lag1
    - z_autocorr_lag2
    - run_mean
    - run_var
    - run_min
    - run_max
    - run_skew
    - run_kurtosis
    - freq_mean
    - freq_var
    - freq_min
    - freq_max
    - freq_skew
    - freq_kurtosis

# Training parameters
training:
  test_size: 0.3
  random_seed: 42
  stratify: true

# XGBoost classifier parameters
classifier:
  n_estimators: 600
  max_depth: 6
  learning_rate: 0.05
  subsample: 0.85
  colsample_bytree: 0.8
  objective: "binary:logistic"
  eval_metric: "auc"
  n_jobs: -1
  random_state: 42


# Experiment depth sequences
depth_experiments:
  - name: "D1-D2"
    depths: [1, 2]
  - name: "D1-D2-D3"
    depths: [1, 2, 3]
  - name: "D1-D2-D3-D4"
    depths: [1, 2, 3, 4]
  - name: "D1-D2-D3-D4-D5"
    depths: [1, 2, 3, 4, 5]
  - name: "D1-D2-D3-D4-D5-D6"
    depths: [1, 2, 3, 4, 5, 6]
  - name: "D1-D2-D3-D4-D5-D6-D7"
    depths: [1, 2, 3, 4, 5, 6, 7]
  - name: "D1-D2-D3-D4-D5-D6-D7-D8"
    depths: [1, 2, 3, 4, 5, 6, 7, 8]

# Alternative depth experiments (starting from different depths)
alternative_depth_experiments:
  - name: "D2-D3-D4-D5-D6-D7-D8"
    depths: [2, 3, 4, 5, 6, 7, 8]
  - name: "D3-D4-D5-D6-D7-D8"
    depths: [3, 4, 5, 6, 7, 8]
  - name: "D4-D5-D6-D7-D8"
    depths: [4, 5, 6, 7, 8]
  - name: "D5-D6-D7-D8"
    depths: [5, 6, 7, 8]
  - name: "D6-D7-D8"
    depths: [6, 7, 8]
  - name: "D7-D8"
    depths: [7, 8]

# Output paths
output:
  base_dir: "results"
  dataset_dir: "data"
  watermarked_dir: "watermarked"
  paraphrased_dir: "paraphrased"
  detection_dir: "detection"
  combined_dir: "combined"
  rolling_window_dir: "rolling_window_stats"
  pss_results_dir: "pss_results"
